# Generated by Django 5.1.1 on 2024-10-08 13:24

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texts',
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={},
        ),
        migrations.AddField(
            model_name='photos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to),
        ),
        migrations.AlterField(
            model_name='photos',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='photos',
            name='path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='country_prod',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='photos',
            table=None,
        ),
    ]
