# Generated by Django 5.1.1 on 2024-10-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_delete_texts_alter_photos_options_photos_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.AlterModelTable(
            name='photos',
            table='photos',
        ),
    ]
