# Generated by Django 5.1.4 on 2024-12-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_seolinks_collections_collection_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seolinks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seolinks',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seolinks',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
