# Generated by Django 5.1.5 on 2025-01-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_collections_collection_url_seolinks_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'ordering': ['order'], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['order'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='seolinks',
            options={'verbose_name': 'Seo link', 'verbose_name_plural': 'Seo links'},
        ),
        migrations.AddField(
            model_name='collections',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
