# Generated by Django 5.1.5 on 2025-01-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_collections_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='collection_url',
            field=models.CharField(blank=True, db_column='collection_url', max_length=255, null=True),
        ),
    ]
