# Generated by Django 5.1.7 on 2025-03-10 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_collections_collection_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='collections',
            name='order',
        ),
        migrations.RemoveField(
            model_name='collections',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='collection_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='order',
        ),
        migrations.AddField(
            model_name='collections',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='shop.products'),
        ),
        migrations.AddField(
            model_name='photos',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop.collections'),
        ),
    ]
