# Generated by Django 5.1.7 on 2025-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_products_options_products_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'ordering': ['order'], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AddField(
            model_name='collections',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
