# Generated by Django 5.1.7 on 2025-04-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_collections_options_collections_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seo_texts',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
