# Generated by Django 5.1.7 on 2025-04-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_products_seo_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='seo_texts',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
