# Generated by Django 5.1.7 on 2025-04-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_products_seo_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='seo_texts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
